# This file is part of addfips.
# http://github.com/fitnr/addfips

# Licensed under the GPL-v3.0 license:
# http://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016, fitnr <fitnr@fakeisthenewreal>

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - pypy

before_install: pip install coverage codecov

install: python setup.py install

script: coverage run setup.py test

after_success: codecov
